### ISSUE TITLE
The word "мэнеджер" in modern Russian is written with the second letter "е"

### ISSUE THREAD

**Issue by CoffeeSquanderer** [ArtemManukyan/BSA#1]
There are a few times when a word "мэнеджер" was used in the text. Maybe this word was acceptable in 1937's SU, but in modern Russian this word is written like "менеджер".

**Comment by CoffeeSquanderer** [comment]
Fixed it in the last commit.
BTW, feel kinda awkward by speaking to myself.

**Comment by volodymyr-kushnir** [comment]
No worries, [people do that](https://media.giphy.com/media/xT9KVL8aGkaekYkoiA/giphy.gif). Especially those in Binary Studio Academy. You could search GitHub with "BSA" or "Binary Studio Academy" and order by *recently updated* to see for yourself — whole lot of people talking to themselves.
