### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by volodymyr-kushnir** [ArtemManukyan/BSA#2]
Hi. How about adding a nice **README.md** maybe? With the links to the articles, description of the repository, that kind of things? Just a suggestion, you could use a separate branch for that. You could also commit with **"Fixes #2"** as commit message, you could also create a Pull Request for yourself using GitHub's "New pull request" feature.

**Comment by CoffeeSquanderer** [comment]
I'll definitely do that, thanks.
